---
title: " "
output: pdf_document
header-includes:
  - \usepackage{float}
  - \usepackage{sectsty}
---

# Introduction

Quantified self-tracking is to monitor and track human-related data such as biological, physical, behavioral or environmental information (Swan, 2009). Two principles often come together with quantified self-tracking are ‘self-knowledge through numbers’ (Ruckenstein, 2015; Schüll, 2016;Swan, 2012) and ‘self-optimisation’(Choe et al., 2014:1147;). There could be an endless list of things to measure but QS concentrate on finding a meaningful insights of QS data and leverage that knowledge to change and improve human life. With that in mind, we as a group of three came to design our quantified self experiment project to explore general idea, knowledge, tools, techniques and experiences.

To explore and understand QS extensively, a variety of areas as Individuals, for the Small Group, and for a Large Cohort data set were tracked and analyzed in this experiment to further explore the following questions:

1. What did you do? We investigate the effects of range of variables on changing human emotions and behaviours.

2. How did you do? How limitation of tracking tools or bad practices of member could affect data quality issues in quantified self tracking?

3. What did you learn? Through investigating the relationships in data, it could provide insights into one’s own life.

A few discussions about data privacy and ethics is included as an extended part. It is necessary to clarify privacy standards for how personal data is used in all QS experiments, especially in experiments with sensitive personal information of group members.